# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scaffold_pico 1.1.8 ruby lib

Gem::Specification.new do |spec|
  spec.name = "scaffold_pico".freeze
  spec.version = "1.1.8"

  spec.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if spec.respond_to? :required_rubygems_version=
  spec.require_paths = ["lib".freeze]
  spec.authors = ["gudata".freeze]
  spec.date = "2018-05-10"
  spec.description = "Scaffolding".freeze
  spec.email = "i.bardarov@gmail.com".freeze
  spec.executables = ["scaffold_pico".freeze]
  spec.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  spec.files = [
    "lib/scaffold/cli.rb",
    "lib/scaffold/erb_context.rb",
    "lib/scaffold/generators/base_generator.rb",
    "lib/scaffold/generators/controller_generator.rb",
    "lib/scaffold/generators/fabricator_generator.rb",
    "lib/scaffold/generators/locales_generator.rb",
    "lib/scaffold/generators/models_generator.rb",
    "lib/scaffold/generators/routes_generator.rb",
    "lib/scaffold/generators/views_generator.rb",
    "lib/scaffold/main.rb",
    "lib/scaffold/models/resource.rb",
    "lib/scaffold/rails.rb",
    "lib/scaffold/services/controller.rb",
    "lib/scaffold/services/nested_in_resources.rb",
    "lib/scaffold/services/path.rb",
    "lib/scaffold/services/resource.rb",
    "lib/scaffold/services/route.rb",
    "lib/scaffold/services/view.rb",
    "lib/scaffold/template_engines/slim.rb",
    "lib/scaffold_pico.rb",
    "lib/templates/pico/controller.rb.erb",
    "lib/templates/pico/fabricators/fabrication.rb.erb",
    "lib/templates/pico/locales/bg.scaffold_pico.yml.erb",
    "lib/templates/pico/locales/en.scaffold_pico.yml.erb",
    "lib/templates/pico/model.rb.erb",
    "lib/templates/pico/search.rb.erb",
    "lib/templates/pico/views/materialize/slim/_form.html.slim.erb",
    "lib/templates/pico/views/materialize/slim/edit.html.slim.erb",
    "lib/templates/pico/views/materialize/slim/index.html.slim.erb",
    "lib/templates/pico/views/materialize/slim/new.html.slim.erb",
    "lib/templates/pico/views/materialize/slim/show.html.slim.erb",
    "lib/templates/pico/views/zurb/slim/_form.html.slim.erb",
    "lib/templates/pico/views/zurb/slim/edit.html.slim.erb",
    "lib/templates/pico/views/zurb/slim/index.html.slim.erb",
    "lib/templates/pico/views/zurb/slim/new.html.slim.erb",
    "lib/templates/pico/views/zurb/slim/show.html.slim.erb"
  ]
  spec.homepage = "http://github.com/gudata/scaffold_pico".freeze
  spec.licenses = ["MIT".freeze]
  spec.rubygems_version = "2.5.2.2".freeze
  spec.summary = "Scaffold should be simple".freeze

  spec.metadata = {
    'source_code_uri' => "http://github.com/gudata/scaffold_pico",
    'bug_tracker_uri' => "http://github.com/gudata/scaffold_pico/issues",
    'allowed_push_host' => 'https://gems.rifiniti.com',
  }

  spec.cert_chain  = ['certs/gudata.pem']
  spec.signing_key = File.expand_path("~/.ssh/gems/gem-private_key.pem") if $0 =~ /gem\z/


  if spec.respond_to? :specification_version then
    spec.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      spec.add_runtime_dependency(%q<activesupport>.freeze, [">= 0"])
      spec.add_runtime_dependency(%q<choice>.freeze, [">= 0"])
      spec.add_runtime_dependency(%q<require_all>.freeze, [">= 0"])
      spec.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      spec.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      spec.add_dependency(%q<activesupport>.freeze, [">= 0"])
      spec.add_dependency(%q<choice>.freeze, [">= 0"])
      spec.add_dependency(%q<require_all>.freeze, [">= 0"])
      spec.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      spec.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    spec.add_dependency(%q<activesupport>.freeze, [">= 0"])
    spec.add_dependency(%q<choice>.freeze, [">= 0"])
    spec.add_dependency(%q<require_all>.freeze, [">= 0"])
    spec.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    spec.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

